### PR TITLE
Bug hunt and code formatting

### LINKED ISSUE #35: Channel Details Repeat Users
If user A sends 100 messages and user B send 0 messages in a channel that contains 2 users A and B, user A will appear in the channel user's list 100 times, and user B will not be listed at all.

### LINKED ISSUE #45: Get shops by user error
If you run Get Shops by User without that user existing, you get a 500 error

### LINKED ISSUE #46: ItemTypeConfigs is not transmitting Name property

### PR DESCRIPTION
**Pull request by Jeremy-Barnes**
For the love of god, look at this with Ignore Whitespace
image

Fix #46 
Fix #45 
FIx #35

### CODE REVIEW

File: CritterServer/Domains/MessageDomain.cs [hunk 1]
```diff
@@ -199,19 +197,30 @@ private async Task<IEnumerable<MessageDetails>> messageToMessageDetails(IEnumera
         private async Task<List<ChannelDetails>> messagesToChannelInfo(IEnumerable<Message> messages)
         {
             IEnumerable<IGrouping<int, Message>> messagesGroupedByChannel = messages.GroupBy(m => m.ChannelId);
-            
+
             Dictionary<int, Channel> channelIdMap = (await MessageRepo.GetChannels(messagesGroupedByChannel.Select(mgbc => mgbc.Key).ToArray())).ToDictionary(c => c.Id);
```
Comment (Jeremy-Barnes) [inline CritterServer/Domains/MessageDomain.cs:201]: Hey look, real functional changes begin here
