### PR TITLE
Random fixes

### LINKED ISSUE #117: HighLow bugs
Refresh HighLow when :00 or :30 timer finishes, right now you have to refresh on your own and thats stupid

Move "don't bet on X" options to top in Sidebets

### PR DESCRIPTION
**Pull request by Jeremy-Barnes**
Fixes #117 and #122

### CODE REVIEW

**Comment by Jeremy-Barnes** [comment]
Fixes #122 and #117

**Comment by Jeremy-Barnes** [comment]
Fixed #117

File: CritterServer/Domains/AdminDomain.cs [hunk 1]
```diff
@@ -92,7 +92,7 @@ public async Task<List<InventoryItemDetails>> CreateItems(List<InventoryItemDeta
                 }
                 foreach (var item in items)
                 {
-                    newItemIds.AddRange(await InventoryRepo.CreateItems(item.Item.ItemTypeId, null));
+                    newItemIds.AddRange(await InventoryRepo.CreateItems(item.Item.ItemTypeId, Npc.WorldPizzaOrganization));
```
Comment (Jeremy-Barnes) [inline CritterServer/Domains/AdminDomain.cs:95]: Note to self, this is wrong
